# Getting Started

## 1. Tensors

In [1]:
import torch

Construct an uninitialized matrix and a random initialized matrix

In [22]:
x = torch.Tensor(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.3163, 0.6708, 0.4495],
        [0.1824, 0.2914, 0.4037],
        [0.4256, 0.4526, 0.0869],
        [0.8817, 0.1755, 0.0969],
        [0.5852, 0.1764, 0.7063]])


Size and indexing about the matrix

In [23]:
print(x.size())
x[:][0] = 2
print(x)

torch.Size([5, 3])
tensor([[2.0000, 2.0000, 2.0000],
        [0.1824, 0.2914, 0.4037],
        [0.4256, 0.4526, 0.0869],
        [0.8817, 0.1755, 0.0969],
        [0.5852, 0.1764, 0.7063]])
