# Getting Started

## 1. Tensors

In [2]:
import torch

Construct an uninitialized matrix and a random initialized matrix

In [3]:
x = torch.Tensor(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1366, 0.7759, 0.7071],
        [0.6059, 0.0671, 0.3783],
        [0.0293, 0.1983, 0.2193],
        [0.1793, 0.4910, 0.9586],
        [0.8785, 0.1839, 0.7517]])


Size and indexing about the matrix

In [4]:
print(x.size())
x[:][0] = 2
print(x)

torch.Size([5, 3])
tensor([[2.0000, 2.0000, 2.0000],
        [0.6059, 0.0671, 0.3783],
        [0.0293, 0.1983, 0.2193],
        [0.1793, 0.4910, 0.9586],
        [0.8785, 0.1839, 0.7517]])


## 2. Operations

### 2.1 Addition

In [9]:
x = torch.rand(5, 3)
print(x)
y = torch.rand(5, 3)
print(y)
print(x + y)
print(torch.add(x, y))
z = torch.Tensor(5, 3)
torch.add(x, y, out=z)
# Inplace Addition 
y.add_(x)
print(y)
print(x[:, 1])

tensor([[0.7793, 0.4327, 0.4137],
        [0.4840, 0.9560, 0.9287],
        [0.7142, 0.8884, 0.4105],
        [0.5911, 0.2288, 0.6481],
        [0.5330, 0.9034, 0.1341]])
tensor([[0.2196, 0.7517, 0.3657],
        [0.0820, 0.1446, 0.7733],
        [0.9337, 0.9032, 0.3397],
        [0.6379, 0.4340, 0.2165],
        [0.9223, 0.3953, 0.5870]])
tensor([[0.9989, 1.1843, 0.7794],
        [0.5660, 1.1005, 1.7019],
        [1.6479, 1.7917, 0.7502],
        [1.2290, 0.6628, 0.8646],
        [1.4553, 1.2987, 0.7211]])
tensor([[0.9989, 1.1843, 0.7794],
        [0.5660, 1.1005, 1.7019],
        [1.6479, 1.7917, 0.7502],
        [1.2290, 0.6628, 0.8646],
        [1.4553, 1.2987, 0.7211]])
tensor([[0.9989, 1.1843, 0.7794],
        [0.5660, 1.1005, 1.7019],
        [1.6479, 1.7917, 0.7502],
        [1.2290, 0.6628, 0.8646],
        [1.4553, 1.2987, 0.7211]])
tensor([0.4327, 0.9560, 0.8884, 0.2288, 0.9034])
